# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 10, 2, 55, 40, 126218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 10, 2, 55, 40, 126257, tzinfo=utc)),
        ),
    ]
