# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 08:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_runpython'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 8, 13, 51, 162716, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_hour',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='18', max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_min',
            field=models.CharField(choices=[('00', '00'), ('30', '30')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_hour',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default='18', max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_min',
            field=models.CharField(choices=[('00', '00'), ('30', '30')], default='00', max_length=2),
        ),
    ]
