# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 10:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_runpython'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 11, 10, 21, 51, 311793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 11, 10, 21, 51, 311832, tzinfo=utc)),
        ),
    ]
