# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 04:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20171114_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 4, 47, 41, 271399, tzinfo=utc)),
        ),
    ]
