# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 04:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20171119_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 19, 4, 49, 32, 952064, tzinfo=utc)),
        ),
    ]
