# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 11:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20171128_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 29, 11, 56, 50, 602850, tzinfo=utc)),
        ),
    ]
